# Site Settings
locale: "en-US"
title: "Hongyuan Lin's Academic Page"
title_separator: "-"
name: &name "Hongyuan Lin"
description: &description "Ph.D. Candidate at National University of Singapore, specializing in Pricing and Revenue Management, Supply Chain Management, Discrete Choice Models, Data-Driven Decision Making, and Decision Making under Uncertainty."
url: "https://Hongyuan-LIN.github.io"
baseurl: ""
repository: "Hongyuan-LIN/Hongyuan-LIN" # Replace [your-github-username] and [your-repo-name] accordingly
teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: false

# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing (Uncomment and fill in if needed)
# twitter:
#   username:
# facebook:
#   username:
#   app_id:
#   publisher:

# Analytics (Uncomment and fill in if needed)
# analytics:
#   provider: "google-universal"
#   google:
#     tracking_id:

# Site Author
author:
  name: "Hongyuan Lin (林宏远)"
  avatar: "lhy.jpg"
  bio: "Ph.D. Candidate at National University of Singapore. My research interests include Pricing and Revenue Management, Supply Chain Management, Discrete Choice Models, Data-Driven Decision Making, and Decision Making under Uncertainty."
  location: "Singapore"
  email: "lin_hongyuan@u.nus.edu"
  # Add links to your profiles as needed
  # github: ""
  # linkedin: ""
  # google_plus: ""

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# Collections
collections:
  pages:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Singapore

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
